# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f2237911530ca777f0251d2b60945132de5c9b5b2ac49cb0360fb6473a310c6ee35b9ff22360bd3cd9fc9e460ba90082c5178fb8965bdf8e8099b836991c465

test:
  secret_key_base: 57676941cb8fc0cc4e6b4593256e019ed961c3ac350d8bbf4e9e1d58c6b5ae30638c9751177d53b794f8d47f669029942112860f23d27ea93eb2ec9604bd1062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
